name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  MYSQL_DATABASE: url_shortener
  MYSQL_ROOT_PASSWORD: url-shorterner-password
  JAVA_VERSION: 1.17

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_DB: ${{ env.MYSQL_DB }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.17
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Build with Macen
        run: mvn package -DskipTests --file pom.xml
      - name: Test with Maven
        run: mvn test
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: url-shortener-1.0-SNAPSHOT.jar
          path: target/